### ISSUE TITLE
Calculate heights by growth habit in species properties

### ISSUE THREAD

**Issue by nstauffer** [Landscape-Data-Commons/terradactyl#146]
Currently the heights are grouped based on the field designation of woody or herbaceous using the "type" variable coming out of the gather functions. This should be changed to use the GrowthHabitSub variable because a species' woody and nonwoody designations may vary by region.

**Comment by smccord** [comment]
We went round and round on this for the first version of calcs. Ultimately we decided to defer to the type the crew saw in the field, but if there was disagreement I think we decided to just throw out the height calc because you don't know if it's a growth habit mismatch or a recording error. Less of an issue with newer data because Survey123 constrains it, but I guess I stand by the original call to use "type".

**Comment by nstauffer** [comment]
This is fine as-is and will remain unchanged.
